name = "leo-app-backend"
main = "src/index.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "leo-app-db"
database_id = "6fd07e72-3055-43cd-a5d0-4c9800f741e9"
preview_database_id = "DB"
